### ISSUE TITLE
No reinstallation of a deleted working device possible.

### ISSUE THREAD

**Issue by Mark481971** [CJNE/ha-sunspec#104]
Hello together,

I have deleted a devices what works so that I can reduce the query time. Unfortunately I can't create the device anymore. I only get the error message "aborted". No entry is made in the logs

What can/must I do?

**Comment by CJNE** [comment]
Hi! Sorry for the late reply to this. I'm not sure what this problem can be, did you find a way around it?

**Comment by Mark481971** [comment]
With the new version the problem was solved.

**Comment by CJNE** [comment]
Great! Closing this.
