### ISSUE TITLE
Interval 30sec

### ISSUE THREAD

**Issue by thecem** [CJNE/ha-sunspec#16]
**Is your feature request related to a problem? Please describe.**
 Update Interval should be configure able

**Describe the solution you'd like**
Maybe a setting per device or a central setting for:
update-interval: 10 sec

**Describe alternatives you've considered**

**Additional context**

Is there an option? What is the interval?

thanks a lot!

**Comment by CJNE** [comment]
Thanks for the suggestion! It has been implemented in version 0.0.5, published just now.

**Comment by thecem** [comment]
Thanks a lot!
Interval of “0” is default and so 30 sec?

**Comment by CJNE** [comment]
Yes 30 is the default, it's probably showing 0 for you since you already had it set up, a little bug that should not affect functionality :)

**Comment by thecem** [comment]
Thx!
