### ISSUE TITLE
Support for long term statistics

### ISSUE THREAD

**Issue by avegao** [CJNE/ha-sunspec#26]
**Is your feature request related to a problem? Please describe.**
Any of sensors provided with this integrations support long term statistics for use with the new Energy panel in HA.

**Describe the solution you'd like**
HA suggest a solution in: [https://www.home-assistant.io/more-info/statistics/](https://www.home-assistant.io/more-info/statistics/)

**Comment by TravisWilder** [comment]
Hello,
My Kaco Solar Inverter was detected well from the Integration.
The Change allowed to select one value "Kaco inverter AC Energy" in the new Energy panel
But also the values for Kaco inverter AC Energy under dev tools shows increasing values the value in the new Energy panel keeps displaying 0
