### ISSUE TITLE
Update 0.0.6 is not available on HACS

### ISSUE THREAD

**Issue by monsterciattolo** [CJNE/ha-sunspec#27]
Hello Expert,
update 0.0.6 is not available as update but i had to manually upgrade using reinstall feature.
Now HACS suggests to upgrade from 0.0.6 to 0.0.5.

Thanks
Marcello

**Comment by thecem** [comment]
Same here! If you need logs pls let me know.

Seems that the something with the tag 0.0.6 is wrong, HACS shows an „update“ from 0.0.6 to 0.0.5 and does not inform when 0.0.5 is installed that there is a „new“ version of 0.0.6.
Additional with beta switch on 0.0.6 is not shown in the list.

thanks a lot!

**Comment by CJNE** [comment]
Not sure what went wrong with 0.0.6, the new 0.0.7 is out now and it the update option seems to work from HACS now.
