### ISSUE TITLE
Changed state class for utility meters and more

### ISSUE THREAD

**Issue by Spitfire69** [CJNE/ha-sunspec#36]
According to https://developers.home-assistant.io/blog/2021/08/16/state_class_total/
the sensor_class for energy and last_reset handling should be changed. Temperature sensors seems also to be handled in a new way.

I guess that much is going on at the moment regarding the new energy handling in HA and I’m not 100% sure that mentioed change affects this component, it could be that it only applies to hourly updated sensors.

**Comment by CJNE** [comment]
Thank you for the heads up, i will update to the new state class asap!
