### ISSUE TITLE
Wrong values with Fronius inverter

### ISSUE THREAD

**Issue by dhover** [CJNE/ha-sunspec#40]
## Version of the custom_component

0.0.9

## Describe the bug

The value for AC power for the Fronius inverter are sometimes too high. More than the capacity of the unit.
My panels have a capacity of 1530 Wp.  The values goes as high as 3000 Watt!
It looks the values looks 10 times too high. Also the DC Power values have those spikes.
The DC Voltage and DC Current values seems ok.
What can be wrong?

AC Power
![image](https://user-images.githubusercontent.com/34840601/131211456-c17451c0-17b4-4869-b710-11b5047c5951.png)

AC Current
![image](https://user-images.githubusercontent.com/34840601/131211543-f51a8cc0-0249-430f-a559-60fb1cd38e50.png)

DC Power
![image](https://user-images.githubusercontent.com/34840601/131211558-318d6f55-88ee-4aaa-b76c-b871c5da8ec9.png)

DC Voltage
![image](https://user-images.githubusercontent.com/34840601/131211571-aa308af7-ff57-4216-b8f9-d0a73f0b5feb.png)

DC Current
![image](https://user-images.githubusercontent.com/34840601/131211587-8e7ab721-72ec-4db7-b413-c45de4cb24e5.png)

**Comment by dhover** [comment]
Extra info: I'm using a Fronius Galvo 1.5-1 inverter.

**Comment by dhover** [comment]
I now see there is a similiar issue #14  

`with manifest.json:
"requirements": ["git+https://github.com/thecem/pysunspec2@master#pysunspec2==1.0.5"]`

I've made the suggested change and will examine the values after a day to see if the spikes are gone.

**Comment by dhover** [comment]
The spikes are gone. So the modified pysunspec2 library seems to solve the problem.

**Comment by CJNE** [comment]
Great, let's hope they merge the fix upstream as well soon!
