### ISSUE TITLE
Failed to connect to host

### ISSUE THREAD

**Issue by moorboss** [CJNE/ha-sunspec#49]
I run into the following issue: When trying to setup the sunspec integration when entering the information as required:

Failed to connect to host 192.168.2.222:502 slave 3 - Device responded - not SunSpec register map

I have eabled the TCP port, het is for sure slave 3 and the IP is also correct. The inverter is a SB3000-TL21 and using the latest version of HA and Sunspec integration.

Is my Inverter to old to be integrated and uses different registers, or might something else be wrong. Who can help?

**Comment by CJNE** [comment]
I did some research, according to this document:
https://www.sma.de/fileadmin/content/landingpages/pl/FAQ/SunSpec_Modbus-TI-en-13.xlsx
your inverter should support SunSpec modbus. 
Maybe you need to update it's firmware though, it says "Starting with software package: 2.60.05.R".
Speedwire data module: SWDM-10

If it still don't work with all requirements met then there might be a bug in pysunspec2, the library that this integration relies on, might be similar to issue #18 in which case you should create a bug report at https://github.com/sunspec/pysunspec2
