### ISSUE TITLE
Fullsupport for the Energy Tab

### ISSUE THREAD

**Issue by iStehle** [CJNE/ha-sunspec#51]
I only could use a few of the Sensors for the Energy Tab.
Non from my Inverter only from the AC meter.

this is the Issue HA pointed me to https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

Next week I should have some time to look into this issue.

**Comment by CJNE** [comment]
The only sensors that will work with the energy tab are energy sensors (Wh or kWh). Most inverters have an energy counter that you should be able to use for the energy tab. When you say AC meter, do you mean a device created by this integration? In that case everything is normal.
