### ISSUE TITLE
Wrong values with Fronius inverter

### ISSUE THREAD

**Issue by QbaF** [CJNE/ha-sunspec#66]
[As described in conersation on community forum](https://community.home-assistant.io/t/custom-component-generic-sunspec-modbus-tcp-monitoring-inverter-meter-etc/312739/41?u=qbaf).
(Issue to increase the repair chance as author correctly noticed.)

**Comment by CJNE** [comment]
Not sure if this is still relevant, feel free to re-open if so, and add some more details.

**Comment by QbaF** [comment]
Oh, I missed somehow this answer, sorry. 
From my point of view still nothing changed. I do have still the wrong data in most sensors.

This is example as used on community forum mentioned in first post. That indicate stable 11'668 Watts for few months. And I do have 8.2kWp inverter.

![image](https://user-images.githubusercontent.com/57077178/161989094-c5b28bf1-727d-4b96-987c-38075217668e.png)

What details I can add? I will be more than happy to assist.

**Comment by QbaF** [comment]
@CJNE I am, most probably, unable to reopen the issue which was closed by repo collaborator.
