### ISSUE TITLE
Feature Request: Adjust config flow to allow new IP address for inverter.

### ISSUE THREAD

**Issue by UrZdcw9** [CJNE/ha-sunspec#87]
**Is your feature request related to a problem? Please describe.**
Recently I attempted to change the IP of my inverter, i was migrating the device off a vlan that had external connectivity to one that didnt.  After the address changed, i had to re-establish the integration, set the name and enter all the details.  This resulted in me having to reconfigure the energy dashboard, various other automation and displays, as well as losing the historical data.

**Describe the solution you'd like**
When you click configure on a known integration, it gives you the ability to set the IP address as well as the other current variables.
**Describe alternatives you've considered**
Updating all the places that the data is used; but nothing can replace the lost data :(

**Comment by CJNE** [comment]
Thanks for the suggestion, I'm sorry about your data loss :(. 
The IP address is part of the device identifier, this is why you had data loss when changing it and re-adding. 
So to solve this (apart from modifying config flow) some other information must be used as a unique id. Will investigate further.
