### ISSUE TITLE
Models Reconfiguration 

### ISSUE THREAD

**Issue by wrongisthenewright** [CJNE/ha-sunspec#91]
## Version of the custom_component

0.0.20

## Configuration
![Screenshot from 2022-03-08 00-41-26](https://user-images.githubusercontent.com/42111723/157137050-8e4657ec-945d-468b-80b1-f7fe01c7f413.png)

HA 2022.3.2

Add your logs here.

No new log line is produced

## Describe the bug

After initial configuration I wanted to add meter specific values so I tried to add the 65233 model (Configuration>integrations>sunspec>configure) but the config gui gives an error of malformed input on already configured model

![Screenshot from 2022-03-08 00-51-12](https://user-images.githubusercontent.com/42111723/157138001-4edeb561-1ec1-4456-9726-2e1fbe975c4f.png)
d

**Comment by Mark481971** [comment]
Ihave the same problems in the case I want to change the "Scan Interval".

**Comment by jonasf21** [comment]
Same here...

**Comment by blankey85** [comment]
I also am having the same issue.  I have a secondary question also.  I have a WattNode meter that is SunSpec certified and shows I need models 1, 203, 213 for it to work.  However, in my dropdown for the read models, I can only choose models that start with a "1" (ie 1, 160, 11, 126, etc.). How do I go about adding those models?

**Comment by teampyt** [comment]
Same here, I am unable to change e.g. the poling interval... Can't be much, right?
