### ISSUE TITLE
Data for ECU-R-PRO not matching native interface

### ISSUE THREAD

**Issue by dewi-ny-je** [CJNE/ha-sunspec#99]
The values reported
1) don't match the values from the native web interface
2) the values for both solar panels of each inverter are always the same, even if the native interface offers independent readings.

See screenshots

![image](https://user-images.githubusercontent.com/2866139/161255719-75f6be4f-2747-4864-8e94-2f454e16825b.png)

![image](https://user-images.githubusercontent.com/2866139/161255768-83f960ae-8c5d-4ad6-9da3-ec1c3563ef0d.png)

(the ones from 3 to 6 are not posted for conciseness)

Original interface

<img width="631" alt="image" src="https://user-images.githubusercontent.com/2866139/161256018-72145939-e397-480f-8536-659fe67d2224.png">

**Comment by jeroenkl** [comment]
same issue, waiting for support

**Comment by MartijnVdS** [comment]
ECU-R exposes the inverters, not the separate panels.

However, it does expose the inverters twice, once with integer data + scale factors in model 101/102/103 (single/split/multi phase), once as floats (Sunspec models 111/112/113).

I only have one inverter, so I don't know if each inverter shows up separately, or if it's all added up by the ECU-R into one big "model" object.

**Comment by SenH** [comment]
You need to assign each inverter a different Modbus address on the ECU-R but there is no separate panel data indeed.
<img width="888" alt="Screenshot 2022-11-24 at 21 38 28" src="https://user-images.githubusercontent.com/168986/203860427-d9545515-1b26-4a0f-9b9f-8973a40339d4.png">

**Comment by dewi-ny-je** [comment]
Thanks
